
prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    # "package",
    # "dotnet",
    "golang",
    # "java",
    # "nodejs",
    "python",
    "ruby",
    # "rust",
    # "nix_shell",
    "conda",
    "memory_usage",
    # "aws",
    "kubernetes",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

[kubernetes]
disabled = false
